apiVersion: v1
kind: ConfigMap
metadata:
  name: whoosis-proxy
  labels:
    app: whoosis
data:
  default.conf: |
    server {
        listen      80;
        server_name  _;

        location = /favicon.ico { access_log off; log_not_found off; }
        location /static/ { root /opt/whoosis; }

        location / { proxy_pass http://localhost:4778; }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: whoosis
spec:
  type: NodePort
  selector:
    app: whoosis
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: whoosis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whoosis
    spec:
      volumes:
        - name: whoosis-data
          emptyDir: {}
        - name: proxy-config
          configMap:
            name: whoosis-proxy
      containers:
        - name: whoosis-app
          image: jmckind/whoosis:0.1.0
          ports:
            - containerPort: 4778
          volumeMounts:
            - mountPath: /opt/whoosis
              name: whoosis-data
        - name: whoosis-proxy
          image: nginx:1.13-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /opt/whoosis
              name: whoosis-data
            - mountPath: /etc/nginx/conf.d
              name: proxy-config
      initContainers:
        - name: whoosis-migrate
          image: jmckind/whoosis:0.1.0
          command:
            - django-admin
            - migrate
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: whoosis.settings
          volumeMounts:
            - mountPath: /opt/whoosis
              name: whoosis-data
        - name: whoosis-static
          image: jmckind/whoosis:0.1.0
          command:
            - django-admin
            - collectstatic
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: whoosis.settings
          volumeMounts:
            - mountPath: /opt/whoosis
              name: whoosis-data
