apiVersion: v1
kind: ConfigMap
metadata:
  name: whoosis-proxy
  labels:
    app: whoosis
data:
  default.conf: |
    server {
        listen      80;
        server_name  _;

        location = /favicon.ico { access_log off; log_not_found off; }
        location /static/ { root /opt/whoosis; }

        location / { proxy_pass http://localhost:4778; }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whoosis-app
  labels:
    app: whoosis
data:
  gunicorn.conf: |
    import multiprocessing

    accesslog = '-'
    access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
    bind = '0.0.0.0:4778'
    chdir = '/opt/whoosis'
    django_settings = 'whoosis.settings'
    errorlog = '-'
    proc_name = 'whoosis'
    pythonpath = '/etc/whoosis'
    #workers = multiprocessing.cpu_count() * 2 + 1
    workers = 3
  local_settings.py: |
    DEBUG = False
    DATABASES = {
      'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'whoosis',
        'USER': 'whoosis',
        'PASSWORD': 'notwhoosis',
        'HOST': 'whoosis-db',
        'PORT': '3306',
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: whoosis
  labels:
    app: whoosis
    tier: frontend
spec:
  type: NodePort
  selector:
    app: whoosis
    tier: frontend
    role: www
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: whoosis-app
  labels:
    app: whoosis
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whoosis
        tier: frontend
        role: www
    spec:
      volumes:
        - name: whoosis-data
          emptyDir: {}
        - name: app-config
          configMap:
            name: whoosis-app
        - name: proxy-config
          configMap:
            name: whoosis-proxy
      containers:
        - name: whoosis-app
          image: quay.io/john_mckenzie/whoosis:v0.1.1a3
          ports:
            - containerPort: 4778
          volumeMounts:
            - mountPath: /opt/whoosis
              name: whoosis-data
            - mountPath: /etc/whoosis
              name: app-config
        - name: whoosis-proxy
          image: nginx:1.13-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /opt/whoosis
              name: whoosis-data
            - mountPath: /etc/nginx/conf.d
              name: proxy-config
      initContainers:
        - name: whoosis-migrate
          image: quay.io/john_mckenzie/whoosis:v0.1.1a3
          command:
            - django-admin
            - migrate
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: whoosis.settings
            - name: PYTHONPATH
              value: '/etc/whoosis'
          volumeMounts:
            - mountPath: /opt/whoosis
              name: whoosis-data
            - mountPath: /etc/whoosis
              name: app-config
        - name: whoosis-static
          image: quay.io/john_mckenzie/whoosis:v0.1.1a3
          command:
            - django-admin
            - collectstatic
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: whoosis.settings
            - name: PYTHONPATH
              value: '/etc/whoosis'
          volumeMounts:
            - mountPath: /opt/whoosis
              name: whoosis-data
            - mountPath: /etc/whoosis
              name: app-config
