apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "whoosis.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.database.password }}
  db-password:  {{ .Values.database.password | b64enc | quote }}
  {{ else }}
  db-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
